version: '2'
services:
  mooc-dubbo-mysql:
    extends:
      file: mysql.yml
      service: mooc-dubbo-mysql
    networks:
      mooc-dubbo-net:
        aliases:
          - mysql
  mooc-dubbo-zookeeper:
    extends:
      file: zookeeper.yml
      service: mooc-dubbo-zookeeper
    networks:
      mooc-dubbo-net:
        aliases:
          - zookeeper
  mooc-redis:
    extends:
      file: redis.yml
      service: mooc-dubbo-redis
    networks:
      mooc-dubbo-net:
        aliases:
          - redis
  mooc-dubbo-dubbo:
    image: xinmeng/dubbo-admin:2.0.0
    depends_on:
      - mooc-dubbo-zookeeper
    environment:
      - ZOOKEEPER=zookeeper:2181
      - ROOT_PASS=root
      - GUEST_PASS=guest
    ports:
      - 7001:7001
    networks:
      mooc-dubbo-net:
        aliases:
          - dubbo
networks:
  mooc-dubbo-net: