version: '2'
services:
  mooc-dubbo-zookeeper:
    extends:
      file: zookeeper.yml
      service: mooc-dubbo-zookeeper
    networks:
      mooc-dubbo-net:
        aliases:
          - zookeeper
  mooc-dubbo-dubbo:
    image: xinmeng/dubbo-admin:2.0.0
    environment:
      - ZOOKEEPER=zookeeper:2181
      - ROOT_PASS=root
      - GUEST_PASS=guest
    ports:
      - 7001:7001
    networks:
      mooc-dubbo-net:
        aliases:
          - dubbo         
networks:
  mooc-dubbo-net: