version: '2'
services:
  mooc-dubbo-zookeeper:
    extends:
      file: zookeeper.yml
      service: mooc-dubbo-zookeeper
    networks:
      mooc-dubbo-net:
        aliases:
          - zookeeper
  mooc-dubbo-monitor:
    image: dubbo-monitor-simple:2.0.0
    environment:
      - ZOOKEEPER=zookeeper:2181
    ports:
      - 7000:8080
    networks:
      mooc-dubbo-net:
        aliases:
          - monitor
networks:
  mooc-dubbo-net: