version: '2'
services:
#  mooc-dubbo-zookeeper:
#    extends:
#      file: zookeeper.yml
#      service: mooc-dubbo-zookeeper
#    networks:
#      mooc-dubbo-net:
#        aliases:
#          - zookeeper
  mooc-dubbo-monitor:
    image: mailbyms/dubbo-monitor
    environment:
      - TZ=Asia/Shanghai
      - ZOOKEEPER_ADDRESS=zookeeper:2181
    ports:
      - 7000:8080
      - 7070:7070
    networks:
      mooc-dubbo-net:
        aliases:
          - monitor
networks:
  mooc-dubbo-net: